### PR TITLE
Obfuscate email addresses across the website

### PR DESCRIPTION
**Pull request by zg**
We've been receiving spam for some time now. One way to counter this is to obfuscate the email addresses on our website. This change will not break existing functionality. It makes it more difficult for spam bots to be able to scan our website and find email addresses.

I obfuscated the email addresses using zsh and [a function in my .zshrc](https://github.com/zg/dot_files/blob/master/.zshrc#L66-L69).

### CODE REVIEW

**Comment by chrissprague** [comment]
This change keeps the addresses displayed as they are now but uses escape chars/char ordinal (etc.) to do so? Like how `&nbsp;` renders as a space?

**Comment by zg** [comment]
Correct.

**Comment by zg** [comment]
There is more information here: http://wbwip.com/wbw/emailencoder.html

**Comment by chrissprague** [comment]
Cool. I like the idea, and I'm sure all of us would be happy to cut down on the spam. That said, it seems like it would hurt maintainability a bit. Not that it is difficult to copy and paste an email address text string into one of these manglers when you have to change something, but it's ugly as hell to look at in the source code.

Should get input on this from @RaineForest @khipkin @ChrisLydic etc

**Comment by khipkin** [comment]
@zg Make a js function or something that does this automatically.  Good idea, though!

**Comment by zg** [comment]
Requiring JavaScript would impose restrictions on our users, but if you guys want to take that approach, I can make the appropriate changes.

**Comment by chrissprague** [comment]
Could have a lookup table of email identifiers to address (i.e. `'officers' => 'officers@csc.cs.rit.edu'`) then have whatever function use that, where the 'table' is stored in a file at a common location

**Comment by zg** [comment]
So, perhaps make the Python do the obfuscation? Or maybe I'm not fully understanding you.

**Comment by chrissprague** [comment]
From a discussion with Yawar, take this as an example (we'd use Django templates rather than PHP, but same idea...)

``` html
<html>
 Email officers at: <?php echo obfuscate($email_table['officers']));?>
</html>
```

or (without lookup table)

``` html
<html>
<!-- <a href="">display this</a> -->
 Email officers at: <?php echo obfuscate('officers@csc.cs.rit.edu'));?>
</html>
```

And, yes, if we have js do the obfuscating then by definition the table would have been passed down to the client anyway which would defeat the whole purpose, so it would need to be server-side

**Comment by zg** [comment]
We could use a Django template filter. I found one [here](https://github.com/morninj/django-email-obfuscator).

**Comment by zg** [comment]
Closing this for now. We have to upgrade Django, and the changes will conflict with this PR since we have to include a new module. It's best to start a new PR for this later on.

**Pull request closed without merging**
