### PR TITLE
Fix to Issue 19

### PR DESCRIPTION
**Pull request by RaineForest**
^ title

### CODE REVIEW

**Comment by chrissprague** [comment]
What is the purpose of `title=""`? Can this be accomplished by just not including the `title` attribute in the first place, or is this safer?

**Comment by RaineForest** [comment]
It's to make sure that the title text (the tooltip, the thing specifically pointed out in #19) doesn't appear by setting it to `null`.

**Comment by chrissprague** [comment]
@RaineForest right, but is explicitly saying `title=""` different than just excluding the `title` tag in the first place, and if so, how?

**Comment by RaineForest** [comment]
A null title specifies an empty string, no title is undefined and left to the discretion of the browser

**Pull request merged**
